{{- if or .Values.envConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-config"
  namespace: {{ .Values.namespace }}
  labels:
    {{- tpl (toYaml .Values.labels) . | nindent 4 }}
data:
  {{- if .Values.envConfig -}}
  {{- toYaml .Values.envConfig | nindent 2 }}
  {{- end }}
{{- end }}
---