apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- tpl (toYaml .Values.labels) . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- tpl (toYaml .Values.labels) . | nindent 6 }}
  template:
    metadata:
      name: {{ .Values.name | default .Chart.Name }}
      labels:
        {{- tpl (toYaml .Values.labels) . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range .Values.service.ports }}
            - name: app-port-{{ . }}
              containerPort: {{ . }}
              protocol: TCP
          {{- end }}
          env:
            {{- range $key, $val := .Values.envConfig }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: "{{ $.Values.name | default $.Chart.Name }}-config"
                  key: {{ $key }}
            {{- end }}
            {{- range .Values.secretKeyRef }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  key: {{ .key }}
                  name: {{ .secretRefName }}
            {{- end}}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}