apiVersion: apps/v1
kind: Deployment
metadata:
  name: beaesthetic-consent-service
  namespace: beaesthetic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beaesthetic-consent-service
  template:
    metadata:
      labels:
        app: beaesthetic-consent-service
    spec:
      containers:
        - name: beaesthetic-consent-service
          image: petretiandrea/beaesthetic-consent-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: beaesthetic-consent-service-config
            - secretRef:
                name: mongodb-connection-uri-consents
          resources:
            limits:
              memory: "128Mi"
              cpu: "80m"
            requests:
              memory: "128Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            failureThreshold: 3
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 15