name: Release Insights Microservice

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - insights/**

env:
  TARGET_PLATFORMS: linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build Docker image"
    outputs:
      tag_deploy: ${{ steps.tag_deploy.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Semantic Release (Dry Run)
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.0.2
          tag_format: customer-${version}
          branches: |
            [ 'main', {name: 'dev', channel: 'dev', prerelease: true} ]
          extra_plugins: |
            @semantic-release/commit-analyzer@11.1.0
            @semantic-release/release-notes-generator@12.1.0
            @semantic-release/git@10.0.1
            @semantic-release/github@9.2.6
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Gradle Properties
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          sed -i -e "s/version=.*/version=${{ steps.semantic.outputs.new_release_version }}/g" insights/gradle.properties

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: petretiandrea/insights-service
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}},value=${{ steps.semantic.outputs.new_release_version }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./apps/customer/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.TARGET_PLATFORMS }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.0.2
          tag_format: customer-${version}
          branches: |
            [ 'main',  { name: 'dev', channel: 'dev', prerelease: true }]
          extra_plugins: |
            @semantic-release/commit-analyzer@11.1.0
            @semantic-release/release-notes-generator@12.1.0
            @semantic-release/git@10.0.1
            @semantic-release/github@9.2.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image tag for deploy
        id: tag_deploy
        run: echo "tag=${{ steps.semantic.outputs.new_release_git_tag }}" >> $GITHUB_OUTPUT;

  deploy:
    needs: [ build ]
    name: "Deploy to K8s"
    runs-on: [ self-hosted, prod, arm64 ] # new k8s cluster with arm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.tag_deploy }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm upgrade
        run: |
          helm upgrade "customer-service" \
            --set namespace="beaesthetic" \
            "./apps/customer/helm/" --install --namespace "beaesthetic" --wait --timeout 5m00s --debug
